### ISSUE TITLE
Mariadb docker image builds mysql not mariadb

### ISSUE THREAD

**Issue by timhaak** [kost/docker-alpine#1]
This builds mysql not maria db :)

apk --update add mysql mysql-client

**Comment by kost** [comment]
Hello Tim and thanks for the issue. 

As far as I know, it will install mysql wrappers around MariaDB. Here's the link to the log of the latest build:
https://hub.docker.com/r/k0st/alpine-mariadb/builds/bsod67erp6dfxrfw2gef8e3/

Interesting parts

```
---> ff6a5e96cc5e
Step 2 : RUN apk --update add mysql mysql-client pwgen && rm -f /var/cache/apk/* && echo "Success"
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/11) Installing mariadb-common (5.5.43-r3)
(2/11) Installing libaio (0.3.110-r0)
(3/11) Installing ncurses-terminfo-base (5.9-r3)
(4/11) Installing ncurses-libs (5.9-r3)
(5/11) Installing libgcc (4.9.2-r5)
(6/11) Installing libstdc++ (4.9.2-r5)
(7/11) Installing mariadb (5.5.43-r3)
(8/11) Installing mysql (5.5.43-r3)
(9/11) Installing mariadb-client (5.5.43-r3)
(10/11) Installing mysql-client (5.5.43-r3)
(11/11) Installing pwgen (2.07-r0)
Executing busybox-1.23.2-r0.trigger
OK: 148 MiB in 26 packages
```

If my thoughts are wrong, feel free to let me know. Maybe I should document it better to mention that it will maintain MySQL compatibility?

**Comment by kost** [comment]
Just checked by trying the following:

```
select VERSION();
VERSION()
5.5.43-MariaDB-log
```

So, it is mariadb.

**Comment by timhaak** [comment]
Ah ok thats odd. I assumed as they also have 'mariadb mariadb-client' that you can install that the mysql one would be mysql. 

Sorry :)
