### ISSUE TITLE
Logstash URL Connection reset by peer

### ISSUE THREAD

**Issue by dminca** [kost/docker-alpine#7]
I tried building the `alpine-logstash` image and I got the **403 Forbidden** error
#### Docker Compose log

``` shell
➜  open-source/docker-alpine$ docker-compose up
Creating network "monitordocker_default" with the default driver
Building logstash
Step 1 : FROM jolokia/alpine-jre-8
 ---> cec011f0dc82
Step 2 : MAINTAINER kost, https://github.com/kost/docker-alpine
 ---> Using cache
 ---> 5b71ef2e850b
Step 3 : ENV LOGSTASH_NAME logstash
 ---> Using cache
 ---> ab717b969764
Step 4 : ENV LOGSTASH_VERSION 1.5.3
 ---> Using cache
 ---> 7265715e8c4f
Step 5 : ENV LOGSTASH_URL https://download.elastic.co/$LOGSTASH_NAME/$LOGSTASH_NAME/$LOGSTASH_NAME-$LOGSTASH_VERSION.tar.gz
 ---> Using cache
 ---> 8bfc0f542ea8
Step 6 : ENV LOGSTASH_CONFIG /opt/$LOGSTASH_NAME-$LOGSTASH_VERSION/etc/logstash.json
 ---> Using cache
 ---> 965ea42ed621
Step 7 : RUN apk update     && apk add bash openssl     && mkdir -p /opt     && wget -O /tmp/$LOGSTASH_NAME-$LOGSTASH_VERSION.tar.gz $LOGSTASH_URL     && tar xzf /tmp/$LOGSTASH_NAME-$LOGSTASH_VERSION.tar.gz -C /opt/     && ln -s /opt/$LOGSTASH_NAME-$LOGSTASH_VERSION /opt/$L
OGSTASH_NAME     && rm -rf /tmp/*.tar.gz /var/cache/apk/*     && mkdir -p /scripts/pre-exec.d &&     mkdir /scripts/pre-init.d &&     chmod -R 755 /scripts
 ---> Running in 82bebf3a96e6
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
v3.2.3-319-g03c6d6e [http://dl-4.alpinelinux.org/alpine/v3.2/main]
OK: 5305 distinct packages available
(1/5) Installing ncurses-terminfo-base (5.9-r3)
(2/5) Installing ncurses-libs (5.9-r3)
(3/5) Installing readline (6.3.008-r0)
(4/5) Installing bash (4.3.33-r0)
(5/5) Installing openssl (1.0.2h-r1)
Executing busybox-1.23.2-r0.trigger
OK: 14 MiB in 23 packages
Connecting to download.elastic.co (184.73.218.216:443)
wget: error getting response: Connection reset by peer
ERROR: Service 'logstash' failed to build: The command '/bin/sh -c apk update     && apk add bash openssl     && mkdir -p /opt     && wget -O /tmp/$LOGSTASH_NAME-$LOGSTASH_VERSION.tar.gz $LOGSTASH_URL     && tar xzf /tmp/$LOGSTASH_NAME-$LOGSTASH_VERSION.tar.gz -C /opt/     
&& ln -s /opt/$LOGSTASH_NAME-$LOGSTASH_VERSION /opt/$LOGSTASH_NAME     && rm -rf /tmp/*.tar.gz /var/cache/apk/*     && mkdir -p /scripts/pre-exec.d &&     mkdir /scripts/pre-init.d &&     chmod -R 755 /scripts' returned a non-zero code: 1
```

**Comment by MartinDelVecchio** [comment]
I am seeing this problem as well:

fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/8) Installing ncurses-terminfo-base (5.9-r3)
(2/8) Installing ncurses-libs (5.9-r3)
(3/8) Installing readline (6.3.008-r0)
(4/8) Installing bash (4.3.33-r0)
(5/8) Installing libstdc++ (4.9.2-r6)
(6/8) Installing libuv (1.5.0-r0)
(7/8) Installing nodejs (0.12.10-r0)
(8/8) Installing openssl (1.0.2i-r0)
Executing busybox-1.23.2-r0.trigger
OK: 36 MiB in 26 packages
[i] Building elasticsearch
-O /tmp/elasticsearch-1.7.1.tar.gz https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.tar.gz
**Connecting to download.elastic.co (184.73.218.216:443)
wget: error getting response: Connection reset by peer**

Any ideas on how to fix this?

Thanks.

**Comment by purplesrl** [comment]
sed -i -e "s/wget -O/curl -o/g" -e "s/nodejs bash/nodejs bash curl/g" Dockerfile

Anyway, this is really old, I attached a Dockerfile for 5.2.0 alpine-elk
[Dockerfile.elk.520.txt](https://github.com/kost/docker-alpine/files/752992/Dockerfile.elk.520.txt)

**Comment by dminca** [comment]
@purplesrl push a MR :+1:

**Comment by purplesrl** [comment]
i will see about it. even if installation works elastic 5.x no longer works as root@ so extra mods are needed...

**Comment by purplesrl** [comment]
@dminca 

Here you go:

https://github.com/purplesrl/docker-alpine-elk

there was too much work to modify this one

**Comment by kost** [comment]
Hello!

All Alpine stuff I have moved to:
https://github.com/alpin3/elk

And they are updated.

Best regards,
